networks:
  lab-net:
    name: lab-network
    external: true

services:
  prometheus:
    image: prom/prometheus:v3.4.0
    volumes:
      - ./prometheus:/etc/prometheus
    ports:
      - "9090:9090"
    networks:
      - lab-net

  grafana:
    image: grafana/grafana:12.0.0
    depends_on:
      - prometheus
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    ports:
      - "3000:3000"
    networks:
      - lab-net

  fake-exporter:
    build: ./exporter
    networks:
      - lab-net
    ports:
      - "8000:8000"

volumes:
  grafana-storage:
